# Site settings
title: Sam Elamin
header-img: img/home-bg.jpg
email: hussam.elamin@gmail.com
copyright_name: samelamin
description: "Big Data Engineer. Interested in Big Data, Metrics Driven Development and Real Time Analytics with Apache Spark and BigQuery"
url: "http://samelamin.github.com"
twitter_username: samelamin
github_username:  samelamin
facebook_username:  #
email_username:  hussam.elamin@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
